<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AnalysisLevel>latest</AnalysisLevel>
    <InvariantGlobalization>false</InvariantGlobalization>
    <NeutralLanguage>ja-JP</NeutralLanguage>
    <Company>J2P</Company>
    <Product>J2P - Jw_cad 一括PDF変換ツール</Product>
    <Version>0.1.0</Version>
  </PropertyGroup>

</Project>
