<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RootNamespace>J2P.App</RootNamespace>
    <AssemblyName>J2P</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <SatelliteResourceLanguages>ja</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="WPF-UI" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\J2P.Core\J2P.Core.csproj" />
  </ItemGroup>

</Project>
